### PR TITLE
Only display the CNA variant shown in the table in CIViC tooltip

### LINKED ISSUE #674: Issue with CIVIC and CNA data?
I just noticed an example of an unexpected CIVIC annotation. The alteration is AMP but the CIVIC information is about a DELETION:

image

I thought we were using AMP/DEL info to find a correct match, and if a correct match was not found but some other information about the gene *was* found, we would make the icon grey?

### PR DESCRIPTION
**Pull request by oplantalech**
# What? Why?
Fix #674.

### CODE REVIEW

File: src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx [hunk 1]
```diff
@@ -73,10 +73,10 @@ export default class AnnotationColumnFormatter
     public static hasCivicVariants (copyNumberData:DiscreteCopyNumberData[], civicGenes:ICivicGene, civicVariants:ICivicVariant): boolean
     {
         let geneSymbol: string = copyNumberData[0].gene.hugoGeneSymbol;
-        let geneVariants: {[name: string]: ICivicVariantData} = civicVariants[geneSymbol];
+        let geneVariants:{[name: string]: ICivicVariantData} = getCivicCNAVariants(copyNumberData, geneSymbol, civicVariants);
         let geneEntry: ICivicGeneData = civicGenes[geneSymbol];
 
-        if (geneEntry && !geneVariants) {
+        if (geneEntry && Object.keys(geneVariants).length === 0) {
```
Comment (onursumer) [inline src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx]: I would prefer `_.isEmpty(geneVariants)` here

File: src/shared/components/annotation/CivicCard.tsx [hunk 2]
```diff
@@ -25,15 +25,19 @@ export default class CivicCard extends React.Component<ICivicCardProps, {}> {
...
 
         if (variantMap) {
-            for (let name in variantMap) {
-                let variant = variantMap[name];
-                let entryTypes: string = '';
-                for (let evidenceType in variant.evidence) {
-                    entryTypes += evidenceType.toLowerCase() + ': ' + variant.evidence[evidenceType] + ', ';
-                }
-                entryTypes = entryTypes.slice(0, -2) + '.';
+            if (Object.keys(variantMap).length === 0) {
```
Comment (onursumer) [inline src/shared/components/annotation/CivicCard.tsx]: `_.isEmpty(variantMap)`

File: src/shared/lib/CivicUtils.ts [hunk 3]
```diff
@@ -134,3 +135,21 @@ export function buildCivicEntry(geneEntry: ICivicGeneData, geneVariants: {[name:
         variants: geneVariants
     };
 }
+
+export function getCivicCNAVariants(copyNumberData:DiscreteCopyNumberData[], geneSymbol: string, civicVariants:ICivicVariant): {[name: string]: ICivicVariantData} {
+    let geneVariants: {[name: string]: ICivicVariantData} = {};
+    if (copyNumberData[0].alteration == 2) {
+        for (let alteration in civicVariants[geneSymbol]) {
+            if (alteration == "AMPLIFICATION") {
```
Comment (onursumer) [inline src/shared/lib/CivicUtils.ts]: In general, `===` is safer than `==`

Comment (inodb) [reply src/shared/lib/CivicUtils.ts]: @oplantalech Yes I mentioned this on a previous PR as well I believe, I don't think there's really any reason to use `==` in JS, always use `===`

**Comment by oplantalech** [comment]
@onursumer @inodb Can you approve and merge? Thank you.

**Comment by oplantalech** [comment]
@inodb It should be fixed now, so can you merge the PR?

File: src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.spec.tsx [hunk 4]
```diff
@@ -25,6 +25,8 @@ describe('AnnotationColumnFormatter', () => {
         let cna = getCnaData();
 
         let expectedCivicEntry = getExpectedCnaCivicEntry();
+        
+        console.log(AnnotationColumnFormatter.getCivicEntry(cna, civicGenes, civicVariants));
```
Comment (onursumer) [inline src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.spec.tsx]: I think we should try to avoid using `console.log`

File: src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx [hunk 5]
```diff
@@ -73,10 +73,10 @@ export default class AnnotationColumnFormatter
     {
         let civicEntry = null;
         let geneSymbol: string = copyNumberData[0].gene.hugoGeneSymbol;
-        let geneVariants: {[name: string]: ICivicVariantData} = civicVariants[geneSymbol];
+        let geneVariants:{[name: string]: ICivicVariantData} = getCivicCNAVariants(copyNumberData, geneSymbol, civicVariants);
         let geneEntry: ICivicGeneData = civicGenes[geneSymbol];
         //Only return data for genes with variants or it has a description provided by the Civic API
-        if (geneVariants || (geneEntry && geneEntry.description !== "")) {
+        if ((Object.keys(geneVariants).length !== 0) || geneEntry && geneEntry.description !== "") {
```
Comment (onursumer) [inline src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx]: `_.isEmpty(geneVariants)`?

File: src/shared/components/annotation/CivicCard.spec.tsx [hunk 6]
```diff
@@ -35,7 +35,7 @@ describe('CivicCard', () => {
 
     it('should not have variant', () => {
         const wrapper = shallow(<CivicCard {...props}/>);
-        expect(wrapper.find('.civic-card-variant')).to.have.length(0);
+        expect(wrapper.find('.civic-card-variant')).to.have.length(1);
```
Comment (onursumer) [inline src/shared/components/annotation/CivicCard.spec.tsx]: So, the unit test definition claims that `it should not have variant`, but then we expect to have 1 `civic-card-variant`. Seems a bit contradicting to me.

**Comment by onursumer** [comment]
@oplantalech I just requested a few more small changes, can you look into them as well? Thanks.

File: src/shared/components/annotation/CivicCard.spec.tsx (hunk 6 above)
Comment (oplantalech) [reply src/shared/components/annotation/CivicCard.spec.tsx]: Now, with the new implementation, `civic-card-variant` is created when there are no variants, only with the `civic-card-variant-description summary` item. However, other items of this part like `civic-card-variant-header`, `civic-card-variant-name` and `civic-card-variant-entry-types` are not created, so I am going to add this three parts as the test to check if there is a variant or not, I think it would make more sense.

**Comment by oplantalech** [comment]
Thank you @onursumer for your comments. Now everything should be corrected.
